apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testdeployment
  name: testdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testdeployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: testdeployment
    spec:
      containers:
      - image: httpd:alpine3.18
        name: httpd
