apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontenddeployment
  name: frontenddeployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontenddeployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: frontenddeployment
    spec:
      containers:
      - image: httpd:alpine3.18
        name: httpd
